language: python
env:
  matrix:
    - BUILD=VANILLA
    - BUILD=ALL DOCS=true
    # Oldest supported compilers (gcc-4.4)
    - GCC_VERSION=4.4 BUILD=VANILLA
    - GCC_VERSION=4.4 BUILD=VANILLA PAR=openmp
    - GCC_VERSION=4.4 BUILD=VANILLA PAR=openmpi
  global:
    - SELFAWARE_DEBUG=true
python:
  - 2.7
install:
  - env
  - export PREVIOUS=$((${TRAVIS_JOB_NUMBER%.*}-1)).${TRAVIS_JOB_NUMBER#*.}
  - env
  - gem install travis --no-rdoc --no-ri
  - travis version --no-interactive
  - sleep 5
  - travis show --no-interactive ${PREVIOUS} | grep State | grep -e "errored\|failed"
  - sleep 5
  - travis show --no-interactive ${PREVIOUS} --debug
  - sleep 5
  - bin/should_i_run.rb
script:
  - sleep 5
  - bin/should_i_run.rb

jobs:
  include:
    - stage: docker push
      script:
        - echo "Docker build push docker"
        - env

    - stage: docker test
      script:
        - echo "Docker test docker"
        - env
