language: python
env:
  matrix:
    - QUIP_ARCH=linux_x86_64_gfortran BUILD=VANILLA
    - QUIP_ARCH=linux_x86_64_gfortran BUILD=VANILLA GCC_VERSION=5
    - QUIP_ARCH=linux_x86_64_gfortran_openmp BUILD=VANILLA
    - QUIP_ARCH=linux_x86_64_gfortran_openmp BUILD=VANILLA GCC_VERSION=4.9
    - QUIP_ARCH=linux_x86_64_gfortran_openmp BUILD=ALL_NOEXTERNAL
    - QUIP_ARCH=linux_x86_64_gfortran_openmpi BUILD=ALL_NOEXTERNAL GCC_VERSION=4.4
    - QUIP_ARCH=linux_x86_64_gfortran BUILD=ALL DOCS=true
    - QUIP_ARCH=linux_x86_64_gfortran BUILD=ALL GCC_VERSION=4.4
    - QUIP_ARCH=linux_x86_64_gfortran_openmp BUILD=ALL
    - QUIP_ARCH=linux_x86_64_gfortran_openmpi BUILD=ALL GCC_VERSION=4.4
matrix:
  allow_failures:
    - env: QUIP_ARCH=linux_x86_64_gfortran BUILD=ALL DOCS=true
    - env: QUIP_ARCH=linux_x86_64_gfortran BUILD=ALL GCC_VERSION=5
    - env: QUIP_ARCH=linux_x86_64_gfortran BUILD=ALL GCC_VERSION=4.4
    - env: QUIP_ARCH=linux_x86_64_gfortran BUILD=ALL GCC_VERSION=4.9
    - env: QUIP_ARCH=linux_x86_64_gfortran_openmp BUILD=ALL
    - env: QUIP_ARCH=linux_x86_64_gfortran_openmp BUILD=ALL GCC_VERSION=5
    - env: QUIP_ARCH=linux_x86_64_gfortran_openmp BUILD=ALL GCC_VERSION=4.4
    - env: QUIP_ARCH=linux_x86_64_gfortran_openmp BUILD=ALL GCC_VERSION=4.9
    - env: QUIP_ARCH=linux_x86_64_gfortran_openmpi BUILD=ALL
    - env: QUIP_ARCH=linux_x86_64_gfortran_openmpi BUILD=ALL GCC_VERSION=5
    - env: QUIP_ARCH=linux_x86_64_gfortran_openmpi BUILD=ALL GCC_VERSION=4.4
    - env: QUIP_ARCH=linux_x86_64_gfortran_openmpi BUILD=ALL GCC_VERSION=4.9
python:
  - 2.6
  - 2.7
install:
  - env
  - export PREVIOUS=echo $((${TRAVIS_JOB_NUMBER%.*}-1)).${TRAVIS_JOB_NUMBER#*.}
  - env
  - gem install travis --no-rdoc --no-ri
  - travis version --no-interactive
  - travis show --no-interactive ${PREVIOUS} --debug
  - bin/should_i_run.rb
script:
  - bin/should_i_run.rb
