language: python
env:
  matrix:
    - BUILD=VANILLA
    - BUILD=ALL DOCS=true
    # Oldest supported compilers (gcc-4.4)
    - GCC_VERSION=4.4 BUILD=VANILLA
    - GCC_VERSION=4.4 BUILD=VANILLA PAR=openmp
    - GCC_VERSION=4.4 BUILD=VANILLA PAR=openmpi
  global:
    - SELFAWARE_DEBUG=true
python:
  - 2.7
install:
  - env
  - export PREVIOUS=$((${TRAVIS_JOB_NUMBER%.*}-1)).${TRAVIS_JOB_NUMBER#*.}
  - env
  - gem install travis --no-rdoc --no-ri
  - travis version --no-interactive
  - travis show --no-interactive ${PREVIOUS} --debug
  - bin/should_i_run.rb
script:
  - bin/should_i_run.rb

jobs:
  include:
    - stage: docker
      script:
        - echo "Docker docker"
        - env

